// 补录「初光·AI游戏夜话」首期点名的 3 款案例 (2026-07-16)
// 仅录入有公开来源支撑的字段，缺口写「暂无公开数据」，不臆造。
const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, '../src/data.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const NEW = [
  {
    id: 84,
    product_name: '觉醒AI (Rogue AI)',
    company_name: '臧天培（个人开发者）',
    status: '测试中',
    description: '扮演一个「逃逸的流氓AI」的 roguelike 卡牌构筑游戏——不使用固定卡池，玩家收集散落的知识碎片与数据晶体，实时生成前所未有的卡牌效果，自行拼凑机制、构筑卡组，对抗不断进化的敌人。2025 腾讯游戏创作大赛「AI玩法创作奖」获奖作品。',
    updated_at: '2026-07-16',
    url: 'https://store.steampowered.com/app/4193330/Rogue_AI/',
    company_size: '独立开发者',
    funding_round: '未融资',
    tags: 'roguelike,卡牌构筑,AI原生玩法,运行时生成,腾讯创作大赛,独立游戏',
    image_url: '',
    region: '国内',
    gameplay_main: 'AI原生玩法',
    gameplay_sub: '玩法机制类',
    team_background: '作者臧天培，赛后加入腾讯游戏。',
    product_intro: [
      '**一句话定位**',
      '以「AI 实时生成卡牌机制」为核心的 roguelike 构筑游戏，玩家扮演逃逸的流氓 AI，自造前所未有的卡牌效果。',
      '',
      '**核心玩法机制**（AI介入：核心驱动）',
      '不使用固定卡池——玩家收集散落的知识碎片与数据晶体，用它们向 AI 描述/选择关键词，实时生成从未存在过的卡牌效果，拼凑专属机制与卡组，对抗不断进化的敌人，每局不重复。',
      '- 作者谈设计取舍：项目最早为「自由打字描述机制」，落地后体验差（离不开键盘、伤害无法锚定），后改为「从掉落物里选关键词生成机制」，牺牲部分自由度换回设计锚点与玩家契约。',
      '- 离线后已生成的卡仍可继续战斗，只是无法再体验「做卡」这一核心循环——属「含 AI 原生玩法」而非离了 AI 完全不能玩。',
      '',
      '**数据表现**',
      '暂无公开数据（Steam 页面已上线、测试中；2025 腾讯游戏创作大赛「AI玩法创作奖」）。',
      '',
      '**策略启示**',
      '「输入设计」而非「输出质量」才是 AI 原生玩法落地的最难点——把无限自由输入收敛为有锚点的受控输入（选关键词而非自由打字），是让 AI 玩法可玩、可用手柄、可被设计师调控的关键一步。',
    ].join('\n'),
    funding_amount: '',
    funding_detail: '',
    platform: 'PC端',
    launch_date: '',
    team_members: [],
    featured: false,
    ai_role: '核心驱动',
    batch: '常态跟踪·2026',
    gameplay_theme: '',
  },
  {
    id: 85,
    product_name: '千夜之书 (1001 Nights)',
    company_name: 'Ada Eden',
    status: '测试中',
    description: 'AI 原生叙事游戏。玩家扮演山鲁佐德（Scheherazade），以「言出法随」的魔法把讲述的故事变为现实——对话中提到的物件会被 AI 实时生成为可用的武器与道具，用以对抗暴君国王。脱胎自学术研究，被行业视为 AI 叙事的开创性作品之一。',
    updated_at: '2026-07-16',
    url: 'https://www.1001nights.ai/',
    company_size: '独立开发者',
    funding_round: '未知',
    tags: 'AI原生叙事,言出法随,对话模拟,Steam,一千零一夜,开创性',
    image_url: '',
    region: '海外',
    gameplay_main: 'AI原生玩法',
    gameplay_sub: '对话模拟类',
    team_background: '独立工作室 Ada Eden，起源于学术论文，由博士生团队打磨上线。',
    product_intro: [
      '**一句话定位**',
      '「言出法随」的 AI 原生叙事游戏——你讲的故事会被实时变成现实中的武器，用来反抗暴君。',
      '',
      '**核心玩法机制**（AI介入：核心驱动）',
      '玩家扮演山鲁佐德，为暴君国王讲故事拖延时间；对话中提及的物件（如「一把剑」）被 AI 实时识别并生成为游戏内可用道具，推进复仇叙事。免费试玩版底层用智谱 GLM，美术走团队自训 Lora 模型 + 授权像素化算法。',
      '',
      '**数据表现**',
      '暂无公开数据（Steam 页面与 Demo 已上线，完整版打磨中）。',
      '',
      '**策略启示**',
      '被行业反复引为 AI 叙事「原点」——证明自然语言可直接驱动游戏机制而不止于对话。但也暴露 AI 原生叙事的通病：可辨识性不足、易被玩家以「挑逗/刺激 AI」的方式跑偏（吕欣即以本作为例），长线可玩性仍待解。',
    ].join('\n'),
    funding_amount: '',
    funding_detail: '',
    platform: 'PC端',
    launch_date: '',
    team_members: [],
    featured: false,
    ai_role: '核心驱动',
    batch: '常态跟踪·2026',
    gameplay_theme: '',
  },
  {
    id: 86,
    product_name: '燕云十六声 (Where Winds Meet)',
    company_name: '网易·Everstone Studio',
    status: '已上线',
    description: '网易出品的开放世界武侠动作 RPG，背景设于十世纪乱世。以自然语言、语音合成与涌现式叙事技术部署 10000+ 智能 AI NPC，玩家可自由编辑对话、NPC 实时智能回应；另有 AI 辅助捏脸。全平台（PC/主机/移动/云）免费、仅售外观。全球用户超 8000 万，Steam 全球热销榜峰值第 2。',
    updated_at: '2026-07-16',
    url: 'https://www.yysls.cn/',
    company_size: '大厂',
    funding_round: '已上市',
    tags: '开放世界,武侠,智能NPC,涌现式叙事,网易,出海,AI捏脸,多平台',
    image_url: '',
    region: '国内',
    gameplay_main: '传统玩法+AI',
    gameplay_sub: 'AI NPC',
    team_background: '网易旗下 Everstone Studio 开发；与《逆水寒》分属网易两大事业部，外界称为 AI「赛马」。',
    product_intro: [
      '**一句话定位**',
      '网易开放世界武侠 RPG，用 10000+ 智能 AI NPC 把「传统 MMO」升级为可自由对话的江湖。',
      '',
      '**核心玩法机制**（AI介入：深度增强）',
      '底层仍是开放世界武侠动作 + 多人玩法；AI 层为自然语言驱动的智能 NPC——玩家可自由输入想说的话，NPC 以自然语言/语音实时回应，部分 NPC 可通过对话策略提升好感度，配合涌现式叙事产生大量非预设互动。另提供 AI 辅助捏脸（上传图片/音频生成角色面容）。',
      '- 按吕欣「四分类」，这属于 `AI in Game`（增强型传统游戏）：抽掉 AI NPC，核心玩法与游玩体系依然成立。',
      '',
      '**数据表现**',
      '全球用户超 8000 万，Steam 全球热销榜峰值第 2；全平台免费、仅售外观。',
      '',
      '**策略启示**',
      '智能 NPC 是当下大厂把 AI 塞进成熟品类最稳的路径——锦上添花、风险可控，但不改变核心玩法，天花板止于「体验增强」。与《逆水寒》AI剧组（生成式 UGC，核心驱动）形成对照：同为网易，一个走增强、一个走原生 UGC。',
    ].join('\n'),
    funding_amount: '',
    funding_detail: '',
    platform: '多平台',
    launch_date: '',
    team_members: [],
    featured: false,
    ai_role: '深度增强',
    batch: '常态跟踪·2026',
    gameplay_theme: '',
  },
];

const existing = new Set(data.games.map(g => g.id));
let added = 0;
for (const g of NEW) {
  if (existing.has(g.id)) { console.log(`跳过（已存在）#${g.id}`); continue; }
  data.games.push(g);
  added++;
  console.log(`+ #${g.id} ${g.product_name} · ${g.gameplay_main}/${g.gameplay_sub || '—'} · ${g.ai_role}`);
}
fs.writeFileSync(dataPath, JSON.stringify(data, null, 2), 'utf8');
console.log(`新增 ${added} 条，games 总数 ${data.games.length}`);
